<?php

$russiaRegionCodes = [
    ['id' => 'RU.AD', 'name' => 'Adygey', 'alt' => 'Adygeya', 'iso' => 'RU-AD', 'hc' => 'ru-ad', 'hasc' => 'RU.AD', 'a2' => 'AD'],
    ['id' => 'RU.AL', 'name' => 'Gorno-Altay', 'alt' => 'Altay', 'iso' => 'RU-AL', 'hc' => 'ru-as', 'hasc' => 'RU.AL', 'a2' => 'AL'],
    ['id' => 'RU.BA', 'name' => 'Bashkortostan', 'alt' => 'Bashkortostan', 'iso' => 'RU-BA', 'hc' => 'ru-bk', 'hasc' => 'RU.BA', 'a2' => 'BA'],
    ['id' => 'RU.BU', 'name' => 'Buryat', 'alt' => 'Buryatiya', 'iso' => 'RU-BU', 'hc' => 'ru-bu', 'hasc' => 'RU.BU', 'a2' => 'BU'],
    ['id' => 'RU.DA', 'name' => 'Dagestan', 'alt' => 'Dagestan', 'iso' => 'RU-DA', 'hc' => 'ru-da', 'hasc' => 'RU.DA', 'a2' => 'DA'],
    ['id' => 'RU.IN', 'name' => 'Ingush', 'alt' => 'Ingushetiya', 'iso' => 'RU-IN', 'hc' => 'ru-in', 'hasc' => 'RU.IN', 'a2' => 'IN'],
    ['id' => 'RU.KB', 'name' => 'Kabardin-Balkar', 'alt' => 'Kabardino-Balkariya', 'iso' => 'RU-KB', 'hc' => 'ru-kb', 'hasc' => 'RU.KB', 'a2' => 'KB'],
    ['id' => 'RU.KL', 'name' => 'Kalmyk', 'alt' => 'Kalmykiya', 'iso' => 'RU-KL', 'hc' => 'ru-kl', 'hasc' => 'RU.KL', 'a2' => 'KL'],
    ['id' => 'RU.KC', 'name' => 'Karachay-Cherkess', 'alt' => 'Karachayevo-Cherkessiya', 'iso' => 'RU-KC', 'hc' => 'ru-kc', 'hasc' => 'RU.KC', 'a2' => 'KC'],
    ['id' => 'RU.KR', 'name' => 'Karelia', 'alt' => 'Kareliya', 'iso' => 'RU-KR', 'hc' => 'ru-kk', 'hasc' => 'RU.KR', 'a2' => 'KR'],
    ['id' => 'RU.KO', 'name' => 'Komi', 'alt' => 'Komi', 'iso' => 'RU-KO', 'hc' => 'ru-ko', 'hasc' => 'RU.KO', 'a2' => 'KO'],
    ['id' => 'RU.ME', 'name' => 'Mariy-El', 'alt' => 'Respublika Mariy-El', 'iso' => 'RU-ME', 'hc' => 'ru-me', 'hasc' => 'RU.ME', 'a2' => 'ME'],
    ['id' => 'RU.MO', 'name' => 'Mordovia', 'alt' => 'Mordoviya', 'iso' => 'RU-MO', 'hc' => 'ru-mr', 'hasc' => 'RU.MO', 'a2' => 'MO'],
    ['id' => 'RU.SA', 'name' => 'Sakha', 'alt' => 'Sakha (Yakutiya)', 'iso' => 'RU-SA', 'hc' => 'ru-sa', 'hasc' => 'RU.SA', 'a2' => 'SA'],
    ['id' => 'RU.SE', 'name' => 'North Ossetia', 'alt' => 'Severnaya Osetiya-Alaniya', 'iso' => 'RU-SE', 'hc' => 'ru-se', 'hasc' => 'RU.SE', 'a2' => 'SE'],
    ['id' => 'RU.TA', 'name' => 'Tatarstan', 'alt' => 'Tatarstan', 'iso' => 'RU-TA', 'hc' => 'ru-tt', 'hasc' => 'RU.TA', 'a2' => 'TA'],
    ['id' => 'RU.TY', 'name' => 'Tuva', 'alt' => 'Tyva', 'iso' => 'RU-TY', 'hc' => 'ru-tu', 'hasc' => 'RU.TY', 'a2' => 'TY'],
    ['id' => 'RU.UD', 'name' => 'Udmurt', 'alt' => 'Udmurtiya', 'iso' => 'RU-UD', 'hc' => 'ru-ud', 'hasc' => 'RU.UD', 'a2' => 'UD'],
    ['id' => 'RU.KK', 'name' => 'Khakass', 'alt' => 'Khakasiya', 'iso' => 'RU-KK', 'hc' => 'ru-kh', 'hasc' => 'RU.KK', 'a2' => 'KK'],
    ['id' => 'RU.CE', 'name' => 'Chechnya', 'alt' => 'Chechnya', 'iso' => 'RU-CE', 'hc' => 'ru-ce', 'hasc' => 'RU.CE', 'a2' => 'CE'],
    ['id' => 'RU.CU', 'name' => 'Chuvash', 'alt' => 'Chuvashiya', 'iso' => 'RU-CU', 'hc' => 'ru-cv', 'hasc' => 'RU.CU', 'a2' => 'CU'],
    ['id' => 'RU.ALT', 'name' => 'Altay', 'alt' => 'Altayskiy Kray', 'iso' => 'RU-ALT', 'hc' => 'ru-al', 'hasc' => 'RU.AL', 'a2' => 'AL'],
    ['id' => 'RU.ZAB', 'name' => 'Zabaykal'ye', 'alt' => 'Zabaykal'skiy Kray', 'iso' => 'RU-ZAB', 'hc' => 'ru-zb', 'hasc' => 'RU.ZB', 'a2' => 'ZB'],
    ['id' => 'RU.KAM', 'name' => 'Kamchatka', 'alt' => 'Kamchatskiy Kray', 'iso' => 'RU-KAM', 'hc' => 'ru-km', 'hasc' => 'RU.KM', 'a2' => 'KM'],
    ['id' => 'RU.KDA', 'name' => 'Krasnodar', 'alt' => 'Krasnodarskiy Kray', 'iso' => 'RU-KDA', 'hc' => 'ru-kd', 'hasc' => 'RU.KD', 'a2' => 'KD'],
    ['id' => 'RU.KYA', 'name' => 'Krasnoyarsk', 'alt' => 'Krasnoyarskiy Kray', 'iso' => 'RU-KYA', 'hc' => 'ru-ky', 'hasc' => 'RU.KN', 'a2' => 'KY'],
    ['id' => 'RU.PER', 'name' => 'Perm', 'alt' => 'Permskiy Kray', 'iso' => 'RU-PER', 'hc' => 'ru-pe', 'hasc' => 'RU.PE', 'a2' => 'PE'],
    ['id' => 'RU.PRI', 'name' => 'Primor'ye', 'alt' => 'Primorskiy Kray', 'iso' => 'RU-PRI', 'hc' => 'ru-pr', 'hasc' => 'RU.PR', 'a2' => 'PR'],
    ['id' => 'RU.STA', 'name' => 'Stavropol'', 'alt' => 'Stavropol'skiy Kray', 'iso' => 'RU-STA', 'hc' => 'ru-st', 'hasc' => 'RU.ST', 'a2' => 'ST'],
    ['id' => 'RU.KHA', 'name' => 'Khabarovsk', 'alt' => 'Khabarovskiy Kray', 'iso' => 'RU-KHA', 'hc' => 'ru-kh', 'hasc' => 'RU.KH', 'a2' => 'KH'],
    ['id' => 'RU.AMU', 'name' => 'Amur', 'alt' => 'Amurskaya Oblast', 'iso' => 'RU-AMU', 'hc' => 'ru-am', 'hasc' => 'RU.AM', 'a2' => 'AM'],
    ['id' => 'RU.ARK', 'name' => 'Arkhangel'sk', 'alt' => 'Arkhangel'skaya Oblast', 'iso' => 'RU-ARK', 'hc' => 'ru-ar', 'hasc' => 'RU.VO', 'a2' => 'AR'],
    ['id' => 'RU.AST', 'name' => 'Astrakhan'', 'alt' => 'Astrakhanskaya Oblast', 'iso' => 'RU-AST', 'hc' => 'ru-as', 'hasc' => 'RU.AS', 'a2' => 'AS'],
    ['id' => 'RU.BEL', 'name' => 'Belgorod', 'alt' => 'Belgorodskaya Oblast', 'iso' => 'RU-BEL', 'hc' => 'ru-bl', 'hasc' => 'RU.BL', 'a2' => 'BE'],
    ['id' => 'RU.BRY', 'name' => 'Bryansk', 'alt' => 'Bryanskaya Oblast', 'iso' => 'RU-BRY', 'hc' => 'ru-br', 'hasc' => 'RU.BR', 'a2' => 'BR'],
    ['id' => 'RU.VLA', 'name' => 'Vladimir', 'alt' => 'Vladimirskaya Oblast', 'iso' => 'RU-VLA', 'hc' => 'ru-vl', 'hasc' => 'RU.VL', 'a2' => 'VL'],
    ['id' => 'RU.VGG', 'name' => 'Volgograd', 'alt' => 'Volgogradskaya Oblast', 'iso' => 'RU-VGG', 'hc' => 'ru-vg', 'hasc' => 'RU.VG', 'a2' => 'VG'],
    ['id' => 'RU.VLG', 'name' => 'Vologda', 'alt' => 'Vologodskaya Oblast', 'iso' => 'RU-VLG', 'hc' => 'ru-vo', 'hasc' => 'RU.VN', 'a2' => 'VO'],
    ['id' => 'RU.VOR', 'name' => 'Voronezh', 'alt' => 'Voronezhskaya Oblast', 'iso' => 'RU-VOR', 'hc' => 'ru-vr', 'hasc' => 'RU.VR', 'a2' => 'VOR'],
    ['id' => 'RU.IVA', 'name' => 'Ivanovo', 'alt' => 'Ivanovskaya Oblast', 'iso' => 'RU-IVA', 'hc' => 'ru-iv', 'hasc' => 'RU.IV', 'a2' => 'IV'],
    ['id' => 'RU.IRK', 'name' => 'Irkutsk', 'alt' => 'Irkutskaya Oblast', 'iso' => 'RU-IRK', 'hc' => 'ru-ir', 'hasc' => 'RU.IR', 'a2' => 'IR'],
    ['id' => 'RU.KGD', 'name' => 'Kaliningrad', 'alt' => 'Kaliningradskaya Oblast', 'iso' => 'RU-KGD', 'hc' => 'ru-kn', 'hasc' => 'RU.KG', 'a2' => 'KN'],
    ['id' => 'RU.KLU', 'name' => 'Kaluga', 'alt' => 'Kaluzhskaya Oblast', 'iso' => 'RU-KLU', 'hc' => 'ru-kg', 'hasc' => 'RU.KL', 'a2' => 'KG'],
    ['id' => 'RU.KEM', 'name' => 'Kemerovo', 'alt' => 'Kemerovskaya Oblast', 'iso' => 'RU-KEM', 'hc' => 'ru-ke', 'hasc' => 'RU.KE', 'a2' => 'KE'],
    ['id' => 'RU.KIR', 'name' => 'Kirov', 'alt' => 'Kirovskaya Oblast', 'iso' => 'RU-KIR', 'hc' => 'ru-ki', 'hasc' => 'RU.KI', 'a2' => 'KI'],
    ['id' => 'RU.KOS', 'name' => 'Kostroma', 'alt' => 'Kostromskaya Oblast', 'iso' => 'RU-KOS', 'hc' => 'ru-ks', 'hasc' => 'RU.KO', 'a2' => 'KS'],
    ['id' => 'RU.KGN', 'name' => 'Kurgan', 'alt' => 'Kurganskaya Oblast', 'iso' => 'RU-KGN', 'hc' => 'ru-ku', 'hasc' => 'RU.KN', 'a2' => 'KU'],
    ['id' => 'RU.KRS', 'name' => 'Kursk', 'alt' => 'Kurskaya Oblast', 'iso' => 'RU-KRS', 'hc' => 'ru-ku', 'hasc' => 'RU.KS', 'a2' => 'KU'],
    ['id' => 'RU.LEN', 'name' => 'Leningrad', 'alt' => 'Leningradskaya Oblast', 'iso' => 'RU-LEN', 'hc' => 'ru-ln', 'hasc' => 'RU.LN', 'a2' => 'LN'],
    ['id' => 'RU.LIP', 'name' => 'Lipetsk', 'alt' => 'Lipetskaya Oblast', 'iso' => 'RU-LIP', 'hc' => 'ru-lp', 'hasc' => 'RU.LP', 'a2' => 'LP'],
    ['id' => 'RU.MAG', 'name' => 'Magadan', 'alt' => 'Magadanskaya Oblast', 'iso' => 'RU-MAG', 'hc' => 'ru-mg', 'hasc' => 'RU.MG', 'a2' => 'MG'],
    ['id' => 'RU.MOS', 'name' => 'Moskva', 'alt' => 'Moskovskaya Oblast', 'iso' => 'RU-MOS', 'hc' => 'ru-ms', 'hasc' => 'RU.MS', 'a2' => 'MS'],
    ['id' => 'RU.MUR', 'name' => 'Murmansk', 'alt' => 'Murmanskaya Oblast', 'iso' => 'RU-MUR', 'hc' => 'ru-mm', 'hasc' => 'RU.MU', 'a2' => 'MM'],
    ['id' => 'RU.NIZ', 'name' => 'Nizhniy Novgorod', 'alt' => 'Nizhegorodskaya Oblast', 'iso' => 'RU-NIZ', 'hc' => 'ru-nz', 'hasc' => 'RU.NN', 'a2' => 'NZ'],
    ['id' => 'RU.NGR', 'name' => 'Novgorod', 'alt' => 'Novgorodskaya Oblast', 'iso' => 'RU-NGR', 'hc' => 'ru-no', 'hasc' => 'RU.NV', 'a2' => 'NO'],
    ['id' => 'RU.NVS', 'name' => 'Novosibirsk', 'alt' => 'Novosibirskaya Oblast', 'iso' => 'RU-NVS', 'hc' => 'ru-ns', 'hasc' => 'RU.NS', 'a2' => 'NS'],
    ['id' => 'RU.OMS', 'name' => 'Omsk', 'alt' => 'Omskaya Oblast', 'iso' => 'RU-OMS', 'hc' => 'ru-om', 'hasc' => 'RU.OM', 'a2' => 'OM'],
    ['id' => 'RU.ORE', 'name' => 'Orenburg', 'alt' => 'Orenburgskaya Oblast', 'iso' => 'RU-ORE', 'hc' => 'ru-ob', 'hasc' => 'RU.OB', 'a2' => 'OB'],
    ['id' => 'RU.ORL', 'name' => 'Orel', 'alt' => 'Orlovskaya Oblast', 'iso' => 'RU-ORL', 'hc' => 'ru-ol', 'hasc' => 'RU.OR', 'a2' => 'OL'],
    ['id' => 'RU.PNZ', 'name' => 'Penza', 'alt' => 'Penzenskaya Oblast', 'iso' => 'RU-PNZ', 'hc' => 'ru-pz', 'hasc' => 'RU.PZ', 'a2' => 'PZ'],
    ['id' => 'RU.PSK', 'name' => 'Pskov', 'alt' => 'Pskovskaya Oblast', 'iso' => 'RU-PSK', 'hc' => 'ru-ps', 'hasc' => 'RU.PS', 'a2' => 'PS'],
    ['id' => 'RU.ROS', 'name' => 'Rostov', 'alt' => 'Rostovskaya Oblast', 'iso' => 'RU-ROS', 'hc' => 'ru-ro', 'hasc' => 'RU.RO', 'a2' => 'RO'],
    ['id' => 'RU.RYA', 'name' => 'Ryazan\'', 'alt' => 'Ryazanskaya Oblast', 'iso' => 'RU-RYA', 'hc' => 'ru-rz', 'hasc' => 'RU.RZ', 'a2' => 'RZ'],
    ['id' => 'RU.SAM', 'name' => 'Samara', 'alt' => 'Samarskaya Oblast', 'iso' => 'RU-SAM', 'hc' => 'ru-sr', 'hasc' => 'RU.SR', 'a2' => 'SR'],
    ['id' => 'RU.SAR', 'name' => 'Saratov', 'alt' => 'Saratovskaya Oblast', 'iso' => 'RU-SAR', 'hc' => 'ru-sa', 'hasc' => 'RU.SA', 'a2' => 'SA'],
    ['id' => 'RU.SAK', 'name' => 'Sakhalin', 'alt' => 'Sakhalinskaya Oblast', 'iso' => 'RU-SAK', 'hc' => 'ru-sk', 'hasc' => 'RU.SH', 'a2' => 'SK'],
    ['id' => 'RU.SVE', 'name' => 'Sverdlovsk', 'alt' => 'Sverdlovskaya Oblast', 'iso' => 'RU-SVE', 'hc' => 'ru-sv', 'hasc' => 'RU.SV', 'a2' => 'SV'],
    ['id' => 'RU.SMO', 'name' => 'Smolensk', 'alt' => 'Smolenskaya Oblast', 'iso' => 'RU-SMO', 'hc' => 'ru-sm', 'hasc' => 'RU.SM', 'a2' => 'SM'],
    ['id' => 'RU.TAM', 'name' => 'Tambov', 'alt' => 'Tambovskaya Oblast', 'iso' => 'RU-TAM', 'hc' => 'ru-tb', 'hasc' => 'RU.TM', 'a2' => 'TB'],
    ['id' => 'RU.TVE', 'name' => 'Tver\'', 'alt' => 'Tverskaya Oblast', 'iso' => 'RU-TVE', 'hc' => 'ru-tv', 'hasc' => 'RU.TV', 'a2' => 'TV'],
    ['id' => 'RU.TOM', 'name' => 'Tomsk', 'alt' => 'Tomskaya Oblast', 'iso' => 'RU-TOM', 'hc' => 'ru-to', 'hasc' => 'RU.TO', 'a2' => 'TO'],
    ['id' => 'RU.TUL', 'name' => 'Tula', 'alt' => 'Tul'skaya Oblast', 'iso' => 'RU-TUL', 'hc' => 'ru-tl', 'hasc' => 'RU.TL', 'a2' => 'TL'],
    ['id' => 'RU.TYU', 'name' => 'Tyumen\'', 'alt' => 'Tyumenskaya Oblast', 'iso' => 'RU-TYU', 'hc' => 'ru-ty', 'hasc' => 'RU.TY', 'a2' => 'TY'],
    ['id' => 'RU.ULY', 'name' => 'Ulyanovsk', 'alt' => 'Ulyanovskaya Oblast', 'iso' => 'RU-ULY', 'hc' => 'ru-ul', 'hasc' => 'RU.UL', 'a2' => 'UL'],
    ['id' => 'RU.CHE', 'name' => 'Chelyabinsk', 'alt' => 'Chelyabinskaya Oblast', 'iso' => 'RU-CHE', 'hc' => 'ru-cl', 'hasc' => 'RU.CH', 'a2' => 'CL'],
    ['id' => 'RU.YAR', 'name' => 'Yaroslavl\'', 'alt' => 'Yaroslavskaya Oblast', 'iso' => 'RU-YAR', 'hc' => 'ru-ys', 'hasc' => 'RU.YA', 'a2' => 'YS'],
    ['id' => 'RU.MOW', 'name' => 'Moscow City', 'alt' => 'Moskva', 'iso' => 'RU-MOW', 'hc' => 'ru-3637', 'hasc' => '-99', 'a2' => 'NU'],
    ['id' => 'RU.SPE', 'name' => 'Saint Petersburg City', 'alt' => 'Sankt-Peterburg', 'iso' => 'RU-SPE', 'hc' => 'ru-2510', 'hasc' => '-99', 'a2' => 'NU'],
    ['id' => 'RU.SEV', 'name' => 'Sevastopol', 'alt' => 'Sevastopol', 'iso' => 'RU-SEV', 'hc' => 'ru-se', 'hasc' => 'RU.SE', 'a2' => 'SE'],
    ['id' => 'RU.KRY', 'name' => 'Crimea', 'alt' => 'Krym', 'iso' => 'RU-KRY', 'hc' => 'ru-kr', 'hasc' => 'RU.KR', 'a2' => 'KR'],
    ['id' => 'RU.YEV', 'name' => 'Jewish Autonomous Oblast', 'alt' => 'Yevreyskaya Avtonomnaya Oblast', 'iso' => 'RU-YEV', 'hc' => 'ru-yv', 'hasc' => 'RU.YV', 'a2' => 'YV'],
    ['id' => 'RU.NEN', 'name' => 'Nenets', 'alt' => 'Nenetskiy AOk', 'iso' => 'RU-NEN', 'hc' => 'ru-nn', 'hasc' => 'RU.NN', 'a2' => 'NN'],
    ['id' => 'RU.KHM', 'name' => 'Khanty-Mansiy', 'alt' => 'Khanty-Mansiyskiy AOk', 'iso' => 'RU-KHM', 'hc' => 'ru-hm', 'hasc' => 'RU.KH', 'a2' => 'HM'],
    ['id' => 'RU.CHU', 'name' => 'Chukchi', 'alt' => 'Chukotskiy AOk', 'iso' => 'RU-CHU', 'hc' => 'ru-ck', 'hasc' => 'RU.', 'a2' => 'CK'],
    ['id' => 'RU.YAN', 'name' => 'Yamal-Nenets', 'alt' => 'Yamalo-Nenetskiy AOk', 'iso' => 'RU-YAN', 'hc' => 'ru-yn', 'hasc' => 'RU.YN', 'a2' => 'YN'],
];